### ISSUE TITLE
[Bug] 1.18.1无法加卸载插件,修改背包

### ISSUE THREAD

**Issue by FrankHan052176** [neko-craft/NekoMaid#14]
# Describe the bug

如题

## To Reproduce

直接测试

## Expected behavior

none

## Screenshots

![image](https://user-images.githubusercontent.com/48244729/148203203-8c88a684-3128-4b41-ae6e-71f579b94686.png)

## Information

- Minecraft version: **1.18.1**
- Plugin version: **0.2.5**
- Uniporter version: **1.3.3**
- Server core:  purpur-1474

## Additional context

none

**Comment by ShirasawaSama** [comment]
有报错吗 另外uniporter最新版本为1.3.3

**Comment by FrankHan052176** [comment]
> 

没有任何报错,单纯是网页没效果(plugman可以做到禁用插件,其他的依旧不可以),还有就是uniporter是1.3.3我写错了23333
