### ISSUE TITLE
网页端口

### ISSUE THREAD

**Issue by QFLSqfls** [neko-craft/NekoMaid#17]
网页端口是不是要放行
以及我是否可以用frp来操作这步

**Comment by ShirasawaSama** [comment]
是的 需要能允许转发http

**Comment by QFLSqfls** [comment]
那我的ip是否与frp的ip同步？

**Comment by ShirasawaSama** [comment]
是的

**Comment by QFLSqfls** [comment]
应该可以tcp协议吧
type = tcp
local_ip = 127.0.0.1
local_port =25001
remote_port= 41097
以上是frpc.ini文件的部分
我应该修改服务器配置文件的那行东西？

**Comment by QFLSqfls** [comment]
补充
![image](https://user-images.githubusercontent.com/87116340/149648598-4555d105-923f-4f18-acc9-b7c52c931fa5.png)

**Comment by ShirasawaSama** [comment]
tcp也可以 只要放frps的服务器能开放http端口即可

**Comment by QFLSqfls** [comment]
是否需要内网端口和外网端口同步？

**Comment by QFLSqfls** [comment]
我一直连接不上网页

**Comment by QFLSqfls** [comment]
![image](https://user-images.githubusercontent.com/87116340/149648728-593b9880-efcf-4fa2-bb06-09b1c465761d.png)
![image](https://user-images.githubusercontent.com/87116340/149648730-154bfe00-e95f-4180-996c-6f3fbdd4d8e8.png)
这里是否是填写这个地址
github上图片不好查看 我邮箱 wind@lmzj.cf

**Comment by ShirasawaSama** [comment]
你得在配置文件里改，然后输入/nm来获取链接地址

**Comment by QFLSqfls** [comment]
全都修改过了
也重新加载了插件
获取最新的地址 无法访问
我想内网与外网的端口是否需要一致？

**Comment by ShirasawaSama** [comment]
请确认服务器没有阻断http请求
