### ISSUE TITLE
网页端无法显示玩家皮肤

### ISSUE THREAD

**Issue by ZoruaFox** [neko-craft/NekoMaid#18]
问题发生时间节点：约2022.1.28 09:00
问题详情：在此时间点之前可以在网页端查看玩家皮肤，之后只能看到默认皮肤，无法显示正版账号皮肤

截止Issue发布，问题仍在持续。

规范性文本

- Minecraft version: **1.16.5**
- Plugin version: **0.2.5**
- Uniporter version: **1.3.3**
- Server core:

This server is running LoliServer version 1.16.5-cf698da (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.22)

**Comment by ShirasawaSama** [comment]
获取皮肤使用的是 mc-heads.net 的API与插件无关

**Comment by ZoruaFox** [comment]
The related screenshots are as follows.

![Screenshot_20220129_015711_com microsoft emmx](https://user-images.githubusercontent.com/96456728/151597771-a95ea2fe-a2a4-4f61-92c1-d01741acab77.jpg)
![Screenshot_20220129_015718_com microsoft emmx](https://user-images.githubusercontent.com/96456728/151597782-f7101861-f281-47e2-9bcd-1696e52f2ed8.jpg)

**Comment by ZoruaFox** [comment]
> 获取皮肤使用的是 mc-heads.net 的API与插件无关

所以这是mc-heads.net网页问题还是服务端问题呢

**Comment by ShirasawaSama** [comment]
请尝试PC端，可能是无法访问mc-heads.net

**Comment by ZoruaFox** [comment]
> 请尝试PC端，可能是无法访问mc-heads.net

网页端情况与手机版web基本一致
![屏幕截图 2022-01-29 020724](https://user-images.githubusercontent.com/96456728/151599080-b57a18c9-71a6-4e17-b955-fc3e22669622.png)
另，使用中国移动WiFi、中国联通蜂窝数据、中国电信蜂窝数据访问mc-heads.net均显示403Forbidden，挂代理则可以正常访问……

**Comment by ZoruaFox** [comment]
> > 请尝试PC端，可能是无法访问mc-heads.net
> 
> PC端情况与手机版web基本一致 ![屏幕截图 2022-01-29 020724](https://user-images.githubusercontent.com/96456728/151599080-b57a18c9-71a6-4e17-b955-fc3e22669622.png) 另，使用中国移动WiFi、中国联通蜂窝数据、中国电信蜂窝数据访问mc-heads.net均显示403Forbidden，挂代理则可以正常访问……

呃……说实话想知道这个情况是地域网络问题还是“全国性”网络问题，后者的话可能就好解释一点了

**Comment by ShirasawaSama** [comment]
可能是该api屏蔽了国内，具体情况不清楚

**Comment by ZoruaFox** [comment]
这个问题api只是在昨天短暂复活了一下，依然是403forbidden

**Comment by ShirasawaSama** [comment]
> 这个问题api只是在昨天短暂复活了一下，依然是403forbidden

这个api不归我们管，并且在我们插件的配置文件中也提供了修改获取皮肤地址的方法
