### ISSUE TITLE
[Bug]NekoMaid不支持PlugManX

### ISSUE THREAD

**Issue by Seayay** [neko-craft/NekoMaid#22]
# Describe the bug

NekoMaid 不支持 PlugManX

## To Reproduce

1. 删除 PlugMan, 装载 PlugManX
2. 插件热重载功能失效

## Expected behavior

无

## Screenshots

无

## Information

- Minecraft version: **1.18.2**
- Plugin version: **0.2.5**
- Uniporter version: **1.3.3**
- PlugManX version: **2.3.0**
- Server core: Windows 10 (Spigot 1.18.2)

## Additional context

无

**Comment by ShirasawaSama** [comment]
请问是已修复或是未修复

**Comment by luobp1** [comment]
未修复
