### ISSUE TITLE
[Bug]端口问题

### ISSUE THREAD

**Issue by RaymondChang1204** [neko-craft/NekoMaid#24]
# Describe the bug

## To Reproduce

我设置了端口为20201
可是查过channels
发现还是没变
还是25565
现在是只能走nm
走不了单独端口加ip
需要解决方法

## Information

- Minecraft version: 1.18,2
- Plugin version: 0.2.5
- Uniporter version: 1.3.4
- Server core: 运行在(ArcLight)

**Comment by ShirasawaSama** [comment]
修改nekomaid配置中的hostname项
