### ISSUE TITLE
[Bug]无法连接到服务器

### ISSUE THREAD

**Issue by RMSCA** [neko-craft/NekoMaid#27]
# Describe the bug

配置文件仔细的检查过，但是网页显示无法连接到服务器

## Screenshots

<img width="1911" alt="Screen Shot 2022-11-18 at 4 18 36 PM" src="https://user-images.githubusercontent.com/72942610/202823639-71e5039d-dd8a-423c-b8c2-f4d99b0d1395.png">
<img width="445" alt="Screen Shot 2022-11-18 at 4 22 16 PM" src="https://user-images.githubusercontent.com/72942610/202823886-eafe57d5-3586-46b9-94a0-3e4d6fc85684.png">

## Information

- Minecraft version: **1.12.2**
- Plugin version: **0.2.5**
- Uniporter version: **1.3.3-SNAPSHOT**
- Server core: catserver dae70adc

**Comment by ShirasawaSama** [comment]
直接浏览器内打开hostname+端口号看显示什么

**Comment by RMSCA** [comment]
浏览器hostname加25565打不开
<img width="655" alt="Screen Shot 2022-11-18 at 9 51 58 PM" src="https://user-images.githubusercontent.com/72942610/202836750-91df5cde-7558-4f11-b093-649ea8ce2df7.png">

**Comment by ShirasawaSama** [comment]
那就尝试另开端口 按wiki中的说明

**Comment by RMSCA** [comment]
。。找到问题了
换端口的时候才想起来
刚刚换了个平台忘了设置防火墙了
25565一直没开
现在可以正常连接上了
感谢
