### ISSUE TITLE
[Bug]Cannot connect to NekoMaid WebPage on MCDR Server by PaperMinecraft-1.19.3

### ISSUE THREAD

**Issue by DrSmoothl** [neko-craft/NekoMaid#34]
# Describe the bug
在1.19.3中，使用MCDReforged 内置的方法启动服务端后，使用/nm命令获取访问链接后发现不能连接到服务器
MCDReforged：https://github.com/Fallen-Breath/MCDReforged

English Version (Translate from Bing Translator):
In 1.19.3, after starting the server side using the built-in method of MCDReforged, after using the /nm command to get the access link, it was found that it could not connect to the server
MCDReforged Link：https://github.com/Fallen-Breath/MCDReforged

## 复现方式：

1. 使用MCDReforged启动服务端（启动参数：python -m mcdregorged）
2. 启动成功后（Uniporter与NekoMaid均无报错）
3. 使用/nm命令获取访问链接

English Version (Translate from Bing Translator):
##Reproduction method:
 1. Start the server with MCDReforged (startup parameter: python -m mcdregorged)
 2. After successful startup (Uniporter and NekoMaid report no error)
 3. Use the /nm command to get the access link

## Information

- Minecraft version: **1.19.3**
- Plugin version: **0.3.1**
- Uniporter version: **1.3.4-fixed1.19**
- Server core: paper-1.19.3-latestBuild

**Comment by ShirasawaSama** [comment]
应该与mcdr是无关的，你是否修改nekomaid的配置文件中的hostname项?

**Comment by DrSmoothl** [comment]
已解决，谢谢
